# @ Numpy
NumPy is used for working with arrays.

NumPy is short for "Numerical Python", has functions for working in domain of linear algebra, fourier transform, and matrices.

**50x faster than traditional Python lists.**

# -- Installation
if command fails it's already installed like, Anaconda, Spyder etc.

C:\Users\Your Name>pip install numpy

# -- Importing & creation
### create a NumPy ndarray object by using the array() function.
of numpy array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# -- DIMENSIONS IN ARRAYS

### 0-D or Scalars
are the elements in an array. Each value in an array is a 0-D array.

In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


### 1-D 
uni-dimensional or 1-D array.These are the most common and basic arrays.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D
These are often used to represent **matrix or 2nd order tensors.**

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D
An array that has 2-D arrays (matrices) inside

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# + Checking Dimensions
## .ndim
 attribute that returns an integer that tells us how many dimensions the array have.

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# + Higher Dimensional Arrays
## ndmin
When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) #must be 1 but we defined it different

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# -- INDEXING (accessing)
You can access an array element by referring to its index number.

The indexes in **NumPy arrays start with 0**, meaning that the first element has index 0, and the second has index 1 etc.

In [9]:
"""1st element"""
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


### indexing 2D array (accessing)

In [10]:
"""Access the element on the first row, second column:"""
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


### indexing 3D array (accessing)

In [12]:
"""Access the third element of the second array of the first array:"""
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


# +Negative Indexing

In [13]:
"""Print the last element from the 2nd dim:"""
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# -- SLICING
## [start:end:step]
 means taking elements from one given index to another given index.
 
 **remember that starts from 0**

In [18]:
"""from 2 to 5 starting from count 0"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [19]:
"""Slice elements from index 4 to the end of the array:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [20]:
"""from the beginning to index 4 (not included):"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# + Negative Slicing

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# + Step

In [24]:
"""Return every other element from index 1 to index 5, 2 by 2:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


### slicing every element

In [23]:
"""Return every other element from the entire array:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [25]:
"""From the second element, slice elements from index 1 to index 4 (not included):"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [26]:
"""From both elements, return index 2:"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [32]:
"""From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# -- DATA TYPES( in NumPy)

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

# + Checking the Data Type  
## .dtype

In [2]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


# + Definig a Data Type
### dtype

In [3]:
"""Create an array with data type string:"""
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [8]:
""" with data type 4 bytes integer:"""
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# +  Can Not Be Converted?
A non integer string like 'a' can not be converted to integer (will raise an error):

In [9]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# + Converting Data Type on Existing Arrays
### .astype()
 best way to change the data type of an existing array, 
 
 is to make a copy of the array with the **astype()** method.
 
 **astype()** function creates a copy of the array, 
 
 and allows you to specify the data type as a parameter.

In [11]:
"""Change data type from float to integer by using 'i' as parameter value:"""
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [12]:
"""Change data type from integer to boolean:"""
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# -- COPY VS VIEW
**copy** is a new array, and the **view** is just a view of the original array.

in copy = changes made to the original array will not affect the copy.

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# + Check if Array Owns its Data
NumPy array has the attribute base that 

**returns None if the array owns the data.**

Otherwise, the base  attribute refers to the original object.

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
