# @ Numpy
NumPy is used for working with arrays.

NumPy is short for "Numerical Python", has functions for working in domain of linear algebra, fourier transform, and matrices.

**50x faster than traditional Python lists.**

# -- Installation
if command fails it's already installed like, Anaconda, Spyder etc.

C:\Users\Your Name>pip install numpy

# -- Importing & creation
### create a NumPy ndarray object by using the array() function.
of numpy array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# -- DIMENSIONS IN ARRAYS

### 0-D or Scalars
are the elements in an array. Each value in an array is a 0-D array.

In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


### 1-D 
uni-dimensional or 1-D array.These are the most common and basic arrays.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D
These are often used to represent **matrix or 2nd order tensors.**

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D
An array that has 2-D arrays (matrices) inside

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# + Checking Dimensions
## .ndim
 attribute that returns an integer that tells us how many dimensions the array have.

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# + Higher Dimensional Arrays
## ndmin
When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) #must be 1 but we defined it different

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# -- INDEXING (accessing)
You can access an array element by referring to its index number.

The indexes in **NumPy arrays start with 0**, meaning that the first element has index 0, and the second has index 1 etc.

In [9]:
"""1st element"""
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


### indexing 2D array (accessing)

In [10]:
"""Access the element on the first row, second column:"""
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


### indexing 3D array (accessing)

In [12]:
"""Access the third element of the second array of the first array:"""
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


# +Negative Indexing

In [13]:
"""Print the last element from the 2nd dim:"""
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# -- SLICING
## [start:end:step]
 means taking elements from one given index to another given index.
 
 **remember that starts from 0**

In [18]:
"""from 2 to 5 starting from count 0"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [19]:
"""Slice elements from index 4 to the end of the array:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [20]:
"""from the beginning to index 4 (not included):"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# + Negative Slicing

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# + Step

In [24]:
"""Return every other element from index 1 to index 5, 2 by 2:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


### slicing every element

In [23]:
"""Return every other element from the entire array:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [25]:
"""From the second element, slice elements from index 1 to index 4 (not included):"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [26]:
"""From both elements, return index 2:"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [32]:
"""From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
