# @ Numpy
NumPy is used for working with arrays.

NumPy is short for "Numerical Python", has functions for working in domain of linear algebra, fourier transform, and matrices.

**50x faster than traditional Python lists.**

# -- Installation
if command fails it's already installed like, Anaconda, Spyder etc.

C:\Users\Your Name>pip install numpy

# -- Importing & creation
### create a NumPy ndarray object by using the array() function.
of numpy array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# -- DIMENSIONS IN ARRAYS

### 0-D or Scalars
are the elements in an array. Each value in an array is a 0-D array.

In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


### 1-D 
uni-dimensional or 1-D array.These are the most common and basic arrays.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D
These are often used to represent **matrix or 2nd order tensors.**

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D
An array that has 2-D arrays (matrices) inside

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# + Checking Dimensions
## .ndim
 attribute that returns an integer that tells us how many dimensions the array have.

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# + Higher Dimensional Arrays
## ndmin
When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) #must be 1 but we defined it different

[[[[[1 2 3 4]]]]]
number of dimensions : 5
