# @ Numpy
NumPy is used for working with arrays.

NumPy is short for "Numerical Python", has functions for working in domain of linear algebra, fourier transform, and matrices.

**50x faster than traditional Python lists.**

# -- Installation
if command fails it's already installed like, Anaconda, Spyder etc.

C:\Users\Your Name>pip install numpy

# -- Importing & creation
### create a NumPy ndarray object by using the array() function.
of numpy array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# -- DIMENSIONS IN ARRAYS

### 0-D or Scalars
are the elements in an array. Each value in an array is a 0-D array.

In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


### 1-D 
uni-dimensional or 1-D array.These are the most common and basic arrays.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D
These are often used to represent **matrix or 2nd order tensors.**

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D
An array that has 2-D arrays (matrices) inside

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# + Checking Dimensions
## .ndim
 attribute that returns an integer that tells us how many dimensions the array have.

In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# + Higher Dimensional Arrays
## ndmin
When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) #must be 1 but we defined it different

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# -- INDEXING (accessing)
You can access an array element by referring to its index number.

The indexes in **NumPy arrays start with 0**, meaning that the first element has index 0, and the second has index 1 etc.

In [9]:
"""1st element"""
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


### indexing 2D array (accessing)

In [10]:
"""Access the element on the first row, second column:"""
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


### indexing 3D array (accessing)

In [12]:
"""Access the third element of the second array of the first array:"""
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


# +Negative Indexing

In [13]:
"""Print the last element from the 2nd dim:"""
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# -- SLICING
## [start:end:step]
 means taking elements from one given index to another given index.
 
 **remember that starts from 0**

In [18]:
"""from 2 to 5 starting from count 0"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [19]:
"""Slice elements from index 4 to the end of the array:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [20]:
"""from the beginning to index 4 (not included):"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# + Negative Slicing

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# + Step

In [24]:
"""Return every other element from index 1 to index 5, 2 by 2:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


### slicing every element

In [23]:
"""Return every other element from the entire array:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


### Slicing 2-D Arrays

In [25]:
"""From the second element, slice elements from index 1 to index 4 (not included):"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [26]:
"""From both elements, return index 2:"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [32]:
"""From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:"""
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# -- DATA TYPES( in NumPy)

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

# + Checking the Data Type  
## .dtype

In [2]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


# + Definig a Data Type
### dtype

In [3]:
"""Create an array with data type string:"""
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [8]:
""" with data type 4 bytes integer:"""
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# +  Can Not Be Converted?
A non integer string like 'a' can not be converted to integer (will raise an error):

In [9]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# + Converting Data Type on Existing Arrays
### .astype()
 best way to change the data type of an existing array, 
 
 is to make a copy of the array with the **astype()** method.
 
 **astype()** function creates a copy of the array, 
 
 and allows you to specify the data type as a parameter.

In [11]:
"""Change data type from float to integer by using 'i' as parameter value:"""
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [12]:
"""Change data type from integer to boolean:"""
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# -- COPY VS VIEW
**copy** is a new array, and the **view** is just a view of the original array.

in copy = changes made to the original array will not affect the copy.

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# + Check if Array Owns its Data
NumPy array has the attribute base that 

**returns None if the array owns the data.**

Otherwise, the base  attribute refers to the original object.

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# -- ARRAY SHAPE
### .shape
shape of an array is the **number of elements in each dimension.**

In [19]:
"""Print the shape of a 2-D array:"""
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
#2 dimentional  where the first dimension has 2 elements and the second has 4.

(2, 4)


# + defining your shape(dimensions)
### ndmin

In [21]:
"""Create an array with 5 dimensions using ndmin"""
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)
# has 4 dimensions and the fifth has 4 elements

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# -- ARRAY RESHAPE
### reshape()
The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

**as long as the elements required for reshaping are equal in both shapes.**

### Reshape From 1-D to 2-D

In [22]:
"""Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape From 1-D to 3-D

In [23]:
"""1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# + Returns Copy or View?

In [28]:
"""Check if the returned array is a copy or a view:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) #8

print(arr.reshape(2, 4).base)
# it's a view (original) cause returns an array not a none

[1 2 3 4 5 6 7 8]


# + Unknown Dimension
### -1 calulate 4 you
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

**Pass -1 as the value, and NumPy will calculate this number for you.**

In [31]:
"""Convert 1D array with 8 elements, to 3D array with 2x2 elements:"""
import numpy as np
arr = np.array([1,4,6,3,8,9,5,33])

newarr = arr.reshape(2,2,-1)

print(newarr)

[[[ 1  4]
  [ 6  3]]

 [[ 8  9]
  [ 5 33]]]


# + Flattening the arrays
### reshape()
means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

# -- ARRAY ITERATING 
## for
going through elements one by one.
### 1D

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


### 2D

In [2]:
"""Iterate on the elements of the following 2-D array:"""
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


### returning ONLY the scalars of 2D

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


### 3D

In [5]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x) #array of arrays

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### returning ONLY the scalars of 3D

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# + Iterating Arrays Using nditer()
## nditer()
t **solves** some basic issues which we face in **iteration like nested fors**

In [7]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


# + Iterating Array With Different Data Types
### changing types in ITERATION
## op_dtypes
## flags=['buffered']
We can use **op_dtypes** argument and pass it the expected datatype to change the datatype of elements while iterating.

**NumPy does not change the data type of the element in-place** (where the element is in array) **so it needs some other space to perform this action, that extra space is called buffer**, and in order to enable it in nditer() we pass **flags=['buffered'].**

In [10]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']): #it is like inplace = True
  print(x)

b'1'
b'2'
b'3'


# + Iterating With Different STEP Size
## [: , ::2]

In [11]:
"""Iterate through every scalar element of the 2D array skipping 1 element:"""
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


# + Enumerated Iteration Using ndenumerate()
### ENUMERATING ITERATIONS
## ndenumerate()
**mentioning sequence number of somethings one by one.**

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.


In [13]:
"""Enumerate on following 1D arrays elements:"""
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [14]:
"""Enumerate on following 2D array's elements:"""
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# --ARRAY JOIN
putting contents of two or more arrays in a single array.
### JOINING TABLES
## concatenate()
along with the axis. If axis is not explicitly passed, it is taken as 0.

In [16]:
"""join 2 arrays"""
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [23]:
"""Join two 2-D arrays along rows (axis=1):"""
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# + Joining Arrays Using Stack Functions
### STACKING ONE OVER THE OTHER
## stack()
same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which **would result in putting them one over the other**

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [34]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# + Stacking Along Rows
### STACKING HORIZONTAL
## hstack() 
to stack along rows.

In [30]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# + Stacking Along Columns
### STACKING VERTICAL
## vstack()  
to stack along columns.

In [31]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


# + Stacking Along Height (depth)
## dstack() 
to stack along height, which is the same as depth.

In [35]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# --SPLITTING NP ARRAY
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use **array_split()** for splitting arrays, we **pass it the array we want to split and the number of splits.**
## array_split()

In [1]:
"""Split the array in 3 parts:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) # The return value is an array containing three arrays.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [2]:
"""split array in 4 parts"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


**split()** is also used but, if arrays are not equals, it would fail, that's why you use **array_split()**

In [5]:
"""Split the 2-D array into three 2-D arrays."""
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [6]:
"""Split the 2-D array into three 2-D arrays."""
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# + access splitted arrays

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# + split Alog Rows 
## axis =

In [14]:
"""Split the 2-D array into three 2-D arrays along rows.

"""
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### + alternate solution is using
## hsplit() or vsplit()

In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [16]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# --SEARCHING ARRAYS
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the **where()** method.
## where()
#### value is 4

In [17]:
"""Find the indexes where the value is 4:"""
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) #value 4 is represented in indexis BELOW

(array([3, 5, 6], dtype=int64),)


#### values are even 

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


#### values are odd

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


# + Search Sorted 
performs a binary search in the array, and returns the index where the specified value would be inserted **to maintain the search order.**
#### where value 7 should be inserted

In [20]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


# + Search From the (Right Side)
By default the left most index is returned, but we can give **side='right' to return the right most index instead.**
#### where the value 7 should be inserted, starting from the right:

In [21]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


# + Search MULTIPLE values
To search for more than one value, **use an array with the specified values.**
#### where the values 2, 4, and 6 should be inserted:

In [25]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
